# Generated by Django 4.2.6 on 2024-04-18 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptop_shop', '0020_branch_created_at_branch_updated_at_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laptop_shop.branch')),
                ('globalInventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locals', to='inventory.globalinventory')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='laptop_shop.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
