# Generated by Django 4.2.6 on 2024-04-18 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptop_shop', '0020_branch_created_at_branch_updated_at_and_more'),
        ('inventory', '0003_remove_localinventory_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalinventory',
            name='vendor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laptop_shop.vendor'),
        ),
    ]
