# Generated by Django 4.2.3 on 2023-09-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop_shop', '0002_collection_product_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(null=True, upload_to='collection_images/'),
        ),
    ]
