# Generated by Django 4.2.6 on 2024-01-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop_shop', '0010_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(),
        ),
    ]
