# Generated by Django 4.2.6 on 2024-03-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop_shop', '0011_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_compare_to',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
