# Generated by Django 4.2.6 on 2024-03-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop_shop', '0012_product_price_compare_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
