# Generated by Django 4.2.6 on 2024-04-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop_shop', '0017_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
