# Generated by Django 6.0 on 2026-01-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop_shop', '0021_alter_collection_name_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quick_view_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
