name: Django CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up SSH key with passphrase
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

        eval "$(ssh-agent -s)"
        SSH_ASKPASS_SCRIPT=$(mktemp)
        echo "#!/bin/sh" > $SSH_ASKPASS_SCRIPT
        echo "echo '${{ secrets.PARAPHRASE }}'" >> $SSH_ASKPASS_SCRIPT
        chmod +x $SSH_ASKPASS_SCRIPT
        DISPLAY=:0 SSH_ASKPASS=$SSH_ASKPASS_SCRIPT setsid ssh-add ~/.ssh/id_rsa

    - name: Debug SSH Connection
      run: |
        ls -la ~/.ssh
        cat ~/.ssh/id_rsa
        ssh -vT ubuntu@${{ secrets.EC2_HOST }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/sourceCode/mainoint
          git fetch origin
          git checkout master
          git pull origin master
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
        EOF
